### ISSUE TITLE
Update Webhooks docs

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-docs#1020]
https://docs.saleor.io/docs/3.x/developer/extending/apps/asynchronous-webhooks

- Add docs for sync webhooks
- Update async webhooks to use snippets from new app sdk

**Comment by timuric** [comment]
@lkostrowski is this issue still relevant?

**Comment by aniav** [comment]
These seem to have been addressed. Sync webhooks have docs and I see `app-sdk` in various places. Feel free to reopen if that's not the case.
