### ISSUE TITLE
Document CORS

### ISSUE THREAD

**Issue by typeofweb** [saleor/saleor-docs#1040]
CORS questions pop up in Discord or GitHub regularly.
What can we do about it?

```[tasklist]
### Tasks
- [ ] Create a dedicated page about CORS in the docs
- [ ] Make it findable by Googling the error message you get from the browser when there are CORS issues
```

**Comment by krzysztofwolski** [comment]
Related troubleshooting section in the apps https://docs.saleor.io/docs/3.x/developer/extending/apps/developing-apps/troubleshooting#client-side-graphql-requests-are-rejected-due-to-cors-error
