### ISSUE TITLE
Event delivery payload as file not documented

### ISSUE THREAD

**Issue by pitkes22** [saleor/saleor-docs#1329]
The new Saleor 3.20.17+ webhook payload delivery as file behavior https://github.com/saleor/saleor/pull/16552 is not documented.

- [ ] Add `AWS_MEDIA_PRIVATE_BUCKET_NAME` to the [Storing Files on Amazon S3](https://docs.saleor.io/setup/media-s3) page.
- [ ] Add `GS_MEDIA_PRIVATE_BUCKET_NAME` to the [Storing Files on Google Cloud Storage](https://docs.saleor.io/setup/media-gcs#environment-variables) page.
- [ ] Add an "Upgrading From 3.19 To 3.20" page to the **Upgrade Guides** and document this change.
- [ ] Document this change in [Asynchronous Events](https://docs.saleor.io/developer/extending/webhooks/asynchronous-events) or another appropriate page.

**Comment by aniav** [comment]
Thank you @pitkes22 for reporting. We've added an internal task to address these missing bits 🙌
