### ISSUE TITLE
I have got error for should have specific permission `AUTHENTICATED_APP ` but it is not available anywhere in saelor.

### ISSUE THREAD

**Issue by ganeshkuikel** [saleor/saleor-docs#1383]
mutation SET_SHIPPING_ADDRESS($checkout_id: ID!, $first_name: String!, $last_name: String!, $country: CountryCode!, $country_area: String!, $street_address_1: String!, $street_address_2: String, $city: String!, $postal_code: String!, $phone: String!) {
  checkoutShippingAddressUpdate(
    id: $checkout_id
    shippingAddress: {firstName: $first_name, lastName: $last_name, streetAddress1: $street_address_1, streetAddress2: $street_address_2, city: $city, postalCode: $postal_code, country: $country, countryArea: $country_area, phone: $phone, skipValidation: true}
  ) {
    checkout {
      id
      shippingMethods {
        id
        name
        price {
          currency
          amount
        }
        minimumDeliveryDays
        maximumDeliveryDays
      }
      shippingMethod {
        id
        name
      }
      shippingAddress {
        firstName
        lastName
        streetAddress1
        streetAddress2
        postalCode
        phone
        city
        countryArea
        country {
          code
        }
      }
    }
    errors {
      field
      message
    }
  }
} I want to run saelor shipping address update by **skipping validation** when i run normally with checkout id only it gives me an eerror of **To skip address validation, you need following permissions: HANDLE_CHECKOUTS, AUTHENTICATED_APP.** when i pass with admin user with permission of handle checkout I again get error AUTHENTICATED_APP error I don't know how to create from saelor. If anyone has idea how to skip the validation please let me know. 

Thank you!

**Comment by aniav** [comment]
Hey @ganeshkuikel in `AUTHENTICATED_APP` represents an App that has been authenticated with Saleor. You need to create a token with an App scope here:
https://docs.saleor.io/developer/extending/apps/architecture/app-permissions#app-scope

This will allow you to make a call like that. Let me know if this helped!

**Comment by aniav** [comment]
This has been addressed in #1400
