### ISSUE TITLE
Add documentation about reordering

### ISSUE THREAD

**Issue by NyanKiyoshi** [saleor/saleor-docs#33]
Once https://github.com/mirumee/saleor/issues/4353 is closed, we will have a unified way of sorting nodes. We should document this.

But, there is one exception: product images. They don't apply to it as we are only doing operations a few images (3, 10, ..., 15). They take no given positions, but instead takes the list of images to perform an enumeration.

All the other mutations are taking relative sort orders.

**Comment by peelar** [comment]
@NyanKiyoshi I know this is ancient but are we still missing this information?
