### ISSUE TITLE
Split checkout into subpages

### ISSUE THREAD

**Issue by timuric** [saleor/saleor-docs#441]
I think it's time we split https://saleor-docs-6i7u5r4oj-saleorcommerce.vercel.app/docs/3.x/developer/checkout, turn it into a category in the sidebar, leave only the intro in this document, and move every section into its own document under `docs/developer/checkout/*.mdx`.

_Originally posted by @patrys in https://github.com/saleor/saleor-docs/issues/432#issuecomment-1142126241_

**Comment by 2can** [comment]
Done with https://github.com/saleor/saleor-docs/pull/777
