### ISSUE TITLE
Document Saleor's core codebase structure and patterns

### ISSUE THREAD

**Issue by maarcingebala** [saleor/saleor-docs#48]
In the "Contributing Guide" we could document things like:
- structure of a module in Saleor, what files it consists of and what is the purpose of each file (as they're mostly the same for all modules)
- structure of Graphene/GraphQL modules

Some files are very specific (like `utils.py / `actions.py) and it would useful, even for us, to know what are the rules for organizing our functions in those files.

`actions.py` is a good example because it should contain business logic. In the docs, we should then tell what do we mean by that and what is business logic and what isn't.

**Comment by peelar** [comment]
@maarcingebala I am aware this is ancient but are these sections still missing?

**Comment by maarcingebala** [comment]
[Our contribution guide](https://docs.saleor.io/docs/3.x/developer/community/contributing) is actually pretty decent in terms of describing the most important patterns we use in the core, so I guess we can close the issue.
