### ISSUE TITLE
from enum import Enum  class ExampleErrorCode(Enum):     ALREADY_EXISTS = "already_exists"     GRAPHQL_ERROR = "graphql_error"     INVALID = "invalid"     NOT_FOUND = "not_found"     REQUIRED = "required"     UNIQUE = "unique"

### ISSUE THREAD

**Issue by BroYoutMrr** [saleor/saleor-docs#575]
from enum import Enum

class ExampleErrorCode(Enum):
    ALREADY_EXISTS = "already_exists"
    GRAPHQL_ERROR = "graphql_error"
    INVALID = "invalid"
    NOT_FOUND = "not_found"
    REQUIRED = "required"
    UNIQUE = "unique"

**Comment by CossackDex** [comment]
Hi @BroYoutMrr, 
You need to provide us with a more detailed description.
