### ISSUE TITLE
Add "community resources" for Saleor Deployments 

### ISSUE THREAD

**Issue by lkostrowski** [saleor/saleor-docs#597]
Rel
https://docs.saleor.io/docs/3.x/developer/running-saleor/docker

At the moment, Deploying saleor is nested in "local development" and it doesn't provide any introduction page

![Zrzut ekranu 2022-11-22 o 13 17 57](https://user-images.githubusercontent.com/9268745/203311884-b8427719-001e-40e9-a741-16e792e7a4ed.png)

Probably it should be improved:
1. Maybe extract deployment to be at the same level as "local development"
2. Add a root page for deployment, with generic information 
3. Add a page with community examples/resources, including https://github.com/skymoore/saleor-platform-k8s-kustomize

**Comment by peelar** [comment]
@lkostrowski How about:
- Replace "Platform" with "Local development" - as this is currently the only item.
- Keep "Deployment" inside "Local development" - as you can only deploy a non-cloud (so local) instance.
- Add a root page for deployment with generic information. Make "Community resources" part of the root page.
  - Question: Is there anything specific you have in mind that should be here?

**Comment by lkostrowski** [comment]
> 

Yup, its fine, structure is a subject of change in the future anyway

>About the "root page for deployment with generic information". Is there anything specific you have in mind that should be here?

Sometimes I want to send a link do "saleor deployment" but we don't have page like this at the moment, so it's a one thing. Another can information that Saleor is open source but the easiest way to use it is Saleor Cloud. Then, some community resources. We can also mentions that our services are provided with Docker images but infrastructure setup is outside of Saleor scope
