### ISSUE TITLE
Add list of all synchronous webhook events

### ISSUE THREAD

**Issue by peelar** [saleor/saleor-docs#640]
In the "Asynchronous Webhooks" page, we have [a list](https://docs.saleor.io/docs/3.x/developer/extending/apps/asynchronous-webhooks#available-webhook-events) of all the available async webhook.s

We don't have the list in the ["Synchronous Webhooks" article](https://docs.saleor.io/docs/3.x/developer/extending/apps/synchronous-webhooks/key-concepts). We should add it.

The list is here: https://docs.saleor.io/docs/3.x/api-reference/enums/webhook-event-type-sync-enum#code-style-fontweight-normal-webhookeventtypesyncenumborder_calculate_taxesbcode

**Comment by 2can** [comment]
@peelar I think it's done, can you verify?

**Comment by peelar** [comment]
@2can yup, done
