### ISSUE TITLE
Menu clipping issues with reduced motion OS settings

### ISSUE THREAD

**Issue by timuric** [saleor/saleor-docs#757]
Steps to reproduce:
Enable reduce motion on Mac 
<img width="731" alt="image" src="https://user-images.githubusercontent.com/4006792/235673827-3377aa62-b066-4297-9e4d-8b729126a9e5.png">

Open and collapse 4th level menu items, for example:

https://docs.saleor.io/docs/3.x/developer/extending/apps/synchronous-webhooks/key-concepts

1. Close the collapsible "Synchronous Webhooks"
2. Close the collapsible "Webhooks"
3. Reopen the collapsible "Webhooks"
4. Reopen collapsible "Synchronous Webhooks"

**Comment by aniav** [comment]
This is no longer an issue after recent visual changes ✨
