### ISSUE TITLE
Add docs on migration from Payments to Transactions (Plugins to Apps)

### ISSUE THREAD

**Issue by typeofweb** [saleor/saleor-docs#806]
- [ ] Write migration guide from Plugins to Apps
- [x] Announce Plugins deprecation date
- [x] Update docs to say that plugins ~~are~~ will be deprecated and when
- [x] Link from Adyen Plugin docs to Adyen App docs and suggest using it instead
- [x] Link from Stripe Plugin docs to Stripe App docs and suggest using it instead
- [ ] …

**Comment by aniav** [comment]
Each Plugin will have a separate migration guide when we introduce an App replacement. It's already the case for apps we do recommend in place of a plugin. I'll close this issue to avoid non-closable issues.
