### ISSUE TITLE
Correct description of the `checkout` query

### ISSUE THREAD

**Issue by timuric** [saleor/saleor-docs#816]
Incorrect description of query
<img width="1028" alt="image" src="https://github.com/saleor/saleor-docs/assets/4006792/f4bd9e07-77ad-4780-9a5f-77fbe1f6ab70">

Describe the behavior of access control of checkouts (anonymous vs authenticated)

**Comment by korycins** [comment]
Merged on core side. Next api-reference bump should improve the description.
