### ISSUE TITLE
Undocumented ENABLE_SSL environment variable

### ISSUE THREAD

**Issue by pitkes22** [saleor/saleor-docs#822]
The **ENABLE_SSL** environment variable is not mentioned in the documentation but it is essential when deploying to production behind a reverse proxy with HTTPS. It is used [in multiple places](https://github.com/saleor/saleor/blob/1d21b8fd1a2cd196481216ab092fb858cafdf8da/saleor/core/utils/__init__.py#L31) when constructing the absolute URL of the API, for [example in the `iss` parameter inside the JWT token](https://github.com/saleor/auth-sdk/issues/5).

**Comment by 2can** [comment]
@pitkes22 #716 has been merged and it introduced `ENABLE_SSL` to the docs https://docs.saleor.io/docs/3.x/setup/configuration#enable_ssl
