### ISSUE TITLE
Document Order lifecycle

### ISSUE THREAD

**Issue by peelar** [saleor/saleor-docs#870]
I think we should add a “Guides” (or rather a “concept”) page for Orders in Saleor.

When you search for “order” in the docs search, the results are “queries” order and “objects” order, both technical reference-type resources. I think we should have something more general.

The article would be the most useful for me if it described the order lifecycle (with f.e. a state machine for all the states the order can be in).

We currently have the following order events:
- `ORDER_CREATED`
- `ORDER_CONFIRMED`
- `ORDER_FULLY_PAID`
- `ORDER_UPDATED`
- `ORDER_CANCELLED`
- `ORDER_EXPIRED`
- `ORDER_FULFILLED`
- `ORDER_REFUNDED`
- `ORDER_FULLY_REFUNDED`
- `ORDER_METADATA_UPDATED`
- `DRAFT_ORDER_CREATED`
- `DRAFT_ORDER_UPDATED`
- `DRAFT_ORDER_DELETED`

We should document how an order progresses from one state to another and what are the implications of that (e.g., a fulfilled order can’t be canceled).

**Comment by aniav** [comment]
This has been addressed in https://docs.saleor.io/developer/checkout/order-status
