### ISSUE TITLE
Additional permissions in the Storefront API 

### ISSUE THREAD

**Issue by 2can** [saleor/saleor-docs#886]
Currently, Storefront API is a subset of Admin API with filtered-out items requiring permissions.

We should analyze if Storefront API should contain items containing some permissions such as `OWNER` or `AUTHENTICATED_USER`.

mentioned by @korycins in #883 

> I know this is not the scope of this PR, but IMO we need to change this approach, and not include mutations/queries that require OWNER or AUTHENTICATED_USER. Currently, any mutation like set-default-shipping-address for customer, are placed in api-reference, instead of a storefront-api

**Comment by aniav** [comment]
We decided to remove Storefront API all together, so I'll go ahead and close this.
