### ISSUE TITLE
Create a guide for Webhooks

### ISSUE THREAD

**Issue by 2can** [saleor/saleor-docs#929]
Create a guide for Webhooks creation/configuration
- from the Dashboard
- with the Graphql
- from the CLI?

**Comment by timuric** [comment]
Added quickstart that covers configuration via dashboard https://docs.saleor.io/docs/quickstart/api

**Comment by 2can** [comment]
There's also the `Webhook creation` page https://docs.saleor.io/docs/developer/extending/webhooks/creating.
