### ISSUE TITLE
Add info about webhook timeouts

### ISSUE THREAD

**Issue by witoszekdev** [saleor/saleor-docs#949]
[This docs page](https://docs.saleor.io/docs/3.x/developer/extending/apps/architecture/communication-between-app-and-saleor#saleor-synchronous-events) describes how webhooks work in Saleor and it mentions timeout. However, we don't list what the timeout is:

<img width="787" alt="CleanShot 2023-09-20 at 13 14 21@2x" src="https://github.com/saleor/saleor-docs/assets/4144459/e5e5f105-8e1d-462a-b43c-bb811798e263">

In Saleor the timeouts are:
- 10s for async webhooks
- 20s for sync webhooks

https://github.com/saleor/saleor/blob/a0eb8c4f16a751964cae35fa90eb6ead83ab247e/saleor/settings.py#L733

We should add a note about this on this page + perhaps add some more information for App developers to take this into consideration

**Comment by witoszekdev** [comment]
Related: https://github.com/saleor/saleor/issues/13770

**Comment by 2can** [comment]
Done with https://github.com/saleor/saleor-docs/pull/1012/files
