### ISSUE TITLE
Practical refunds guide

### ISSUE THREAD

**Issue by 2can** [saleor/saleor-docs#986]
Based on communication with clients, it seems many of them don’t understand the difference between ‘grant refund’ and ‘issue refund’ and there’s no clear explanation in the docs for it.

It's not just the API calls description, we have that, but we don’t explain the use case at all for two steps, and two buttons, and there is no high-level overview of the whole process, from start to end.

**Comment by aniav** [comment]
This is being addressed two ways: 1. The dashboard is getting a refunds flow lifting in 3.20 (that is going to be released in the next weeks). 2. #1118 added more docs around refunds. I'll go ahead and close this for now.
